WIP: add bats-assert functionality
exercism/bash pull request #539
Opened 2021-09-03 16:15 UTC by glennj

Resolves #536 

The `bats-extra.bash` will be added to every exercise.
Each exercise's test file will be updated to use bats-assert functions.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

2021-09-03 16:21 UTC, glennj commented
For example, "hello world":

The successful test output appearance does not change
```bash
$ bats hello_world_test.sh
 ✓ Say Hi!

1 test, 0 failures
```
If the exit status is non-zero:
```bash
$ cat hello_world.sh
#!/usr/bin/env bash

echo "Hello, World!"
exit 2

$ bats hello_world_test.sh
 ✗ Say Hi!
   (from function `assert_success' in file ./bats-extra.bash, line 409,
    in test file hello_world_test.sh, line 10)
     `assert_success' failed with status 2

   -- command failed --
   status : 2
   output : Hello, World!
   --


1 test, 1 failure

$ echo $?
1
``` 
If the output does not match what's expected:
```bash
$ cat hello_world.sh
#!/usr/bin/env bash

echo "Goodbye, Mars!"

$ bats hello_world_test.sh
 ✗ Say Hi!
   (from function `assert_output' in file ./bats-extra.bash, line 394,
    in test file hello_world_test.sh, line 13)
     `assert_output "Hello, World!"' failed

   -- output differs --
   expected : Hello, World!
   actual   : Goodbye, Mars!
   --


1 test, 1 failure

$ echo $?
1
```

2021-09-03 16:22 UTC, glennj commented
@exercism/bash Thoughts please?

2021-09-03 18:32 UTC, kotp approved these changes
Looks good to me, with one suggestion for the repeated "kv" use in the names to show what the placeholder might be.

2021-09-03 18:32 UTC, kotp commented on exercises/practice/hello-world/bats-extra.bash
> +batslib_print_kv_multi() {
What is `kv` in the name?  And `batslib` or should it be two words, as `bats_lib` for consistency?  It appears most words are separated by underscores throughout.

If `kv` represents "key value" or "key and value" what does the key represent and what does the value represent?

2021-09-03 20:05 UTC, IsaacG requested changes

2021-09-03 20:05 UTC, IsaacG commented on exercises/practice/hello-world/hello_world_test.sh
> +source ./bats-extra.bash
Any test to fail if the file is missing or cannot be sourced?

2021-09-03 20:05 UTC, IsaacG commented on exercises/practice/hello-world/bats-extra.bash
> +# Comments have been removed to save space. See the git repos for full source code.
Is this file entirely upstream code (i.e. I shouldn't bother reviewing) or is it only partial upsteam?

2021-09-03 20:09 UTC, glennj commented on exercises/practice/hello-world/bats-extra.bash
> +batslib_print_kv_multi() {
I didn't write any of that, and I don't indent to change anything in it.

That particular function is at https://github.com/bats-core/bats-support/blob/master/src/output.bash#L136

2021-09-03 20:11 UTC, glennj commented on exercises/practice/hello-world/bats-extra.bash
> +# Comments have been removed to save space. See the git repos for full source code.
It's all of https://github.com/bats-core/bats-support/tree/master/src and https://github.com/bats-core/bats-assert/tree/master/src

2021-09-03 20:17 UTC, glennj commented on exercises/practice/hello-world/hello_world_test.sh
> +source ./bats-extra.bash
Hmm, well if it can't be found then `exercism download` would be broken. If the student accidentally deletes it, then a helpful message to re-download would be useful

2021-09-03 20:30 UTC, glennj commented on exercises/practice/hello-world/hello_world_test.sh
> +source ./bats-extra.bash
I changed `source` to the bats function `load`. If the file does not exist, then
```bash
$ bats hello_world_test.sh
 ✗ File hello_world_test.sh
bats: bats-extra.bash does not exist
   (in test file hello_world_test.sh, line 9)
     `load bats-extra.bash' failed

1 test, 1 failure
```

2021-09-03 23:28 UTC, IsaacG approved these changes

2021-09-03 23:31 UTC, kotp approved these changes

2021-09-03 23:32 UTC, kotp commented
I can see that it is titled WIP, but "convert to draft" is probably a better solution.  It can prevent premature merges.

2021-09-04 02:16 UTC, glennj commented
Phew, all tests passing.

2021-09-04 02:17 UTC, glennj commented
> I can see that it is titled WIP, but "convert to draft" is probably a better solution. It can prevent premature merges.

No longer WIP/draft

2021-09-04 02:25 UTC, glennj commented
Reviewers: coments about the commits here:

commit | msg | notes
-|-|-
dd41d86 | WIP: add bats-assert functionality | convert "hello world"
646c5fd | use bats "load" function instead of "source" | errors out if bats-extra.bash not source-able
05954bd | add bats-extra.bash to all exercises | adding file to all other exercises
ebd194c | transform test scripts to use bats-assert functions | this is big delta and where you'll want to spend your time: convert all test suites to use assert functions
5ae639f | with an associative array, "${map[@]}" order is indeterinate, broke i… | fix to example script for bash 5.1
f2fc14c | in arithmetic, bare map entry with quote in key broke in bash 5.1| fix to example script for bash 5.1
54d7be2 | update workflow, using github cli with auto-pagination, to pull in AL… | update GHA workflow script to work with loads of changes
2495798 | add env var to workflow for auth | update GHA workflow script to work with loads of changes

2021-09-04 02:29 UTC, kotp approved these changes

2021-09-04 17:25 UTC, IsaacG approved these changes

2021-09-04 17:25 UTC, IsaacG commented on .github/workflows/pr.yml
> +          ' | xargs -r bash .github/scripts/pr
You can lose the xargs and just do this in a loop with bash.

```
mapfile -t filenames < <(gh api ...)
for filename in "${filenames[@]}"; do
  bash ... "$filename"
done
```
```

2021-09-04 18:54 UTC, SleeplessByte commented on .github/workflows/pr.yml
> +          ' | xargs -r bash .github/scripts/pr
We _should_ be able to use `git diff` directly:

```shell
git diff --name-only
```

2021-09-04 19:11 UTC, glennj commented on .github/workflows/pr.yml
> +          ' | xargs -r bash .github/scripts/pr
@IsaacG I could, but what's the advantage over xargs? Do we know that the shell used to execute the `run` item is bash so that mapfile is even available?

2021-09-04 19:40 UTC, IsaacG commented on .github/workflows/pr.yml
> +          ' | xargs -r bash .github/scripts/pr
Do we know that the machine has xargs installed? 

`cmd | while read filename ...` is the POSIX-sh version of that if you want to support `sh`. Though at that point, should `xargs` be calling `bash` or `sh`?

2021-09-04 19:49 UTC, glennj commented on .github/workflows/pr.yml
> +          ' | xargs -r bash .github/scripts/pr
> Do we know that the machine has xargs installed? 

Yes: https://github.com/exercism/bash/pull/539/checks?check_run_id=3514619188#step:5:1

2021-09-04 20:13 UTC, merged

2021-09-05 00:46 UTC, MichaelDimmitt commented
cool, thanks for adding this. 

nice idea to save users from needing to install the posix compliant bash in different environments.
since it is posix compliant we can just add the files for them.

and adding the extra file bats-extra.bash that
concatenated bats assert and bats support

In the future maybe a script iterates through all files in the test folder and updates bats-extra.bash if the plugins have an update we want to add. But no need to overengineer at present moment.

definately gives more output to students 👍

2021-09-05 01:35 UTC, glennj commented
Thanks for the inspiration. While I was working on it I was thinking I should apologize: I think I was pretty dismissive about your ideas. So, sorry. Working with the v3 website really revealed the need for better test failure feedback.