test files: rename xxx_test.sh to xxx.bats, fix shebang
exercism/bash pull request #541
Opened 2021-09-15 15:18 UTC by braoult

# pull request template

tests scripts: change extension to .bats, fix shebang.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

2021-09-16 14:19 UTC, iHiD submitted a review, later dismissed
**This shouldn't get merged until https://github.com/exercism/bash-test-runner/pull/27 is merged**

We need to be careful on this. The test runner most support both existing exercises and this new format, and that support must be deployed, before this is merged.

I'm "Requesting Changes" just to block this until the test runner is merged.

2021-09-16 14:21 UTC, iHiD commented
@angelikaTyborska, @neenjaw, @mPizenberg Any advice on this after doing it on your tracks?

2021-09-16 14:37 UTC, braoult commented
> We need to be careful on this. The test runner most support both existing exercises and this new format, and that support must be deployed, before this is merged.

https://github.com/exercism/bash-test-runner/pull/27 supports both old (`xxx_test.sh`) and new (`xxx.bats`) file names. And yes, this PR was planned to be hold until bash-test-runner PR is merged.

2021-09-16 14:43 UTC, mpizenberg commented
tbh I haven't fully taken the time yet to evaluate the implications of the change on the online tooling. The tooling itself in the elm track does not support the old way, only the new one, and the filepaths changes actually occurred a while ago, before starting the work on v3. It's just that I noticed the multiple files issues on the online editor for even older submissions of mine.

2021-09-16 14:47 UTC, braoult commented
> tbh I haven't fully taken the time yet to evaluate the implications of the change on the online tooling. The tooling itself in the elm track does not support the old way, only the new one, and the filepaths changes actually occurred a while ago, before starting the work on v3. It's just that I noticed the multiple files issues on the online editor for even older submissions of mine.

When I discussed about this change on Slack yesterday, I wondered what could be some other side effects, nobody raised the online tooling... Could this be a blocking point ? I don't know at all  how all of this interacts...

2021-09-16 14:55 UTC, mpizenberg commented
Well, the online tooling is composed of the tests runner (seems you took care of that), the analyzer (it will have to take into account both in the future if it's going to be run on old solutions), the representer (which only cares about the solution, not the tests so fine here) and the online editor, which needs to present the solution (and tests for practice exercises) to the user.

So in you case, I think the only point left is to check how is handled the presentation of the tests file in the online editor for practice exercise.

2021-09-16 15:05 UTC, braoult commented
> So in you case, I think the only point left is to check how is handled the presentation of the tests file in the online editor for practice exercise.

Yes.

@iHiD, why the `bash` (student' solution) files would be read-only, and not the `bats`files (tests) ? I am not sure to understand. What we do here is:
- before :
```
student solution: xxx.sh
test program: xxx_test.sh
```
- after :
```
student solution: xxx.sh
test program: test.bats
```

2021-09-16 15:48 UTC, angelikatyborska commented
> @angelikatyborska Any advice on this after doing it on your tracks?

I actually started maintaining the track _after_ this change happened 🤷

2021-09-16 21:24 UTC, braoult commented
My concern here is only : _Where_ and _when_ the online editor gets the list of files to edit from ?
- *where*: Is there some hardcoded names on UI side, or is the list taken from somewhere (likely `.meta/config.json` ?). If it is taken from `config.json`, I don't see any issue (I updated them in this PR). If not, I simply have no clue on what should be done there.
- *when* : I hope the filenames information is part of the student's solution environment (i.e. the `filenames` are determined when the student starts to use UI, and never changed later). Is that the way it works ?

2021-09-17 04:53 UTC, angelikatyborska commented
> where: Is there some hardcoded names on UI side, or is the list taken from somewhere (likely .meta/config.json ?).

It is taken from `.meta/config.json`, the three types of files - "test", "solution", and "editor" (non-editable files). But added to that are the files that the student submitted for the previous solution. Via the web editor they only could have submitted the previous values of `files.solution`, but via the CLI anything.

> when : I hope the filenames information is part of the student's solution environment (i.e. the filenames are determined when the student starts to use UI

@iHiD will know this best, but my understanding is that every solution contains the git SHA of the exercise as it were when the student started the exercise and takes files directly from git from that point in time. However, it can change. The platform shows when a change is done to an exercise and shows you the diff between your version and the new version. Then, you can choose to update your solution to the newest version and I think that changes the SHA which means the student will now get the newest versions of all files, including the new `.meta/config.json`.

2021-09-17 09:37 UTC, iHiD commented
OK, a couple of things.

1. The files are locked to what the student has when they start the exercise, but they are prompted to update when changes are made, at which point they get multiple solution files if the solution file has been renamed. That's because they get all their submitted files, and all the files in the `solution` key.
1. I misunderstood and thought that we were renaming the stubs, not the tests. Sorry. The fact that only the tests are changing makes this less of a concern. I'm not sure what happens when a student updates to the latest version then downloads that update. I doubt it will delete their old tests file, so they'll have both. Will that be ok?

I've now merged the test-runner one so remove my lock on this.

2021-09-17 09:50 UTC, braoult commented
> I'm not sure what happens when a student updates to the latest version then downloads that update. I doubt it will delete their old tests file, so they'll have both. Will that be ok?

Yes: If both files are there, test-runner will use by default the new one (`xxx.bats`). This is done in `bin/run.sh` :
```
    local test_file="${slug//-/_}.bats"
    # test scripts may be (old) xxxx_test.sh
    [[ -f "$test_file" ]] || test_file="${slug//-/_}_test.sh"
```
As the test code itself is unchanged, we are fine here.

2021-09-17 12:27 UTC, glennj requested changes

2021-09-17 12:49 UTC, braoult commented on exercises/shared/.docs/tests.md
>  `bats` will need to be installed.
Ooops. Fixed.

2021-09-17 12:54 UTC, braoult commented on exercises/shared/.docs/tests.md
>  `bats` will need to be installed.
Oh, I also removed ending spaces... Is it OK ?

2021-09-17 13:04 UTC, glennj approved these changes

2021-09-17 13:13 UTC, glennj commented
The workflow is doing this:
```bash
gh api repos/exercism/bash/pulls/541/files --paginate --jq '
  .[] |
    select(.status == "added" or .status == "modified" or .status == "renamed") |
    select(.filename |
    match("\\.(sh|bash|bats)$")) |
    .filename
'
```

2021-09-17 20:33 UTC, glennj commented
@IsaacG I know you have opinions about this subject. Can you review please?

2021-09-17 20:51 UTC, braoult commented
> @IsaacG I know you have opinions about this subject. Can you review please?

Do you mean the extension itself, as seen on Slack (no extension for executable) ?

2021-09-17 21:08 UTC, glennj commented
> Do you mean the extension itself, as seen on Slack (no extension for executable) ?

No, removing the extension will make the pr.yml github workflow harder to make specific.

2021-09-17 21:42 UTC, IsaacG approved these changes
This looks good to me! Thank you for your work.

2021-09-17 21:42 UTC, IsaacG commented on bin/validate_one_exercise
> +bats "${exercise_name}.bats"
Side note/no change requested. In theory, with the fixed shebang. we should be able to give the tests a `+x` and just run them ... but in practice calling `bats` with the filename is probably easier.

2021-09-17 22:00 UTC, braoult commented on bin/validate_one_exercise
> +bats "${exercise_name}.bats"
Exact. I thought about it, but unsure about this `+x` on non *ix-like systems...

2021-09-17 23:05 UTC, glennj commented on bin/validate_one_exercise
> +bats "${exercise_name}.bats"
Also, I don't think that exercism download respects the executable bits.

2021-09-17 23:06 UTC, merged