Update instructions for error handling in bash
exercism/bash pull request #576
Opened 2022-05-08 15:52 UTC by Philosoft

The only way to complete this exercise right now is to read tests. PR adds bare bones instructions on what is required

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

2022-05-08 17:01 UTC, IsaacG commented
> The only way to complete this exercise right now is to read tests.

By and large this is true across multiple tracks and by design, leaning pretty hard into the test-driven development philosophy.

This file is synced directly from the [upstream problem spec](https://github.com/exercism/problem-specifications/blob/main/exercises/error-handling/description.md). **If** we opted to flesh out the instructions, it would need to be done via an amend file.

2022-05-08 19:08 UTC, glennj commented
Philosophically speaking, as exercism promotes TDD, getting students to read the tests is exactly what we should be doing. However, I agree that this exercise is a bit under-documented.

As [documented](https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md), the place to add this track-specific material is in the `exercises/practice/error-handling/.docs/instructions.append.md` file.

As per exercism's [markdown style guide](https://github.com/exercism/docs/blob/main/building/markdown/markdown.md), all markdown files start with a level-1 header. In this case, the process that joins instructions.md and instructions.append.md drop the header from the append file, so just add a placeholder header.

Regarding the text specifically, I'd prefer the instructions to be a bit less explicit

> The goal of this exercise is to consider the _number_ of arguments passed to your program. If there is exactly one argument, print a greeting message. Otherwise print an error message.

2022-05-08 21:54 UTC, Philosoft commented
Ouch. I am sorry. Apparently, I missed mentioning of TDD somewhere. Then maybe there is no need for this change at all 🤔

2022-05-09 17:54 UTC, glennj commented
I think this is still a worthy PR, just needs some changes.

2022-05-09 20:19 UTC, Philosoft commented
@glennj used your text and moved it to `exercises/practice/error-handling/.docs/instructions.append.md` file

2022-05-09 20:50 UTC, glennj requested changes

2022-05-09 20:50 UTC, glennj commented on exercises/practice/error-handling/.docs/instructions.append.md
> +# Specific instructions
The process that generates README (that concatenates instructions.md and instructions.append.md) strips out level-1 headers.

Please start the file with:
```markdown
# Dummy header

## Bash-specific instructions
```
All of the instructions.append.md files in the bash track are similarly incorrect: I'll create an issue to address that.

2022-05-09 21:43 UTC, Philosoft commented on exercises/practice/error-handling/.docs/instructions.append.md
> +# Specific instructions
I wasn't sure that the real heading was needed, but 'Dummy header' seemed out of place 😅

2022-05-12 15:58 UTC, Philosoft commented on exercises/practice/error-handling/.docs/instructions.append.md
> +# Specific instructions
https://github.com/exercism/bash/pull/576/commits/0d523b4e5871249198cf82e7aa517b5de46c6f21 ✅

2022-05-12 16:43 UTC, glennj approved these changes

2022-05-12 16:45 UTC, merged

2022-05-12 16:47 UTC, glennj commented
This is what the instructions look like now:
![image](https://user-images.githubusercontent.com/122470/168127033-84bc387f-4ed7-4d80-9363-e9c8851e85f6.png)

2022-05-12 16:48 UTC, glennj commented
Oops, a typo: `Bash-pecific`. we'll need another PR to fix that.