Update example.sh
exercism/bash pull request #631
Opened 2023-04-29 11:55 UTC by ljsr

This change permit that the program pass correctly the test related with the digits of zero value:  for example the arguments 10 "0" 2 must return 0 or the arguments 10 "0 0 0 0" 4 must return 0 too.  Additionally this change is accord with the null digit: 10 "" 2, the return value must be 0.

# pull request template

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

2023-04-29 14:15 UTC, kotp requested changes
Trailing white space introduced on these two lines should be removed.

2023-04-29 14:15 UTC, kotp commented on exercises/practice/all-your-base/.meta/example.sh
> +
```suggestion

```

2023-04-29 14:15 UTC, kotp commented on exercises/practice/all-your-base/.meta/example.sh
> +
```suggestion

```

2023-04-29 17:46 UTC, glennj commented
Please add the updated test case to this PR, and then we can close the other one.

2023-04-29 19:53 UTC, kotp approved these changes

2023-05-02 18:05 UTC, glennj commented
Work has proceeded in #630

2023-05-02 18:05 UTC, closed without merging