Feat/key features (#469)
exercism/bash pull request #634
Opened 2023-06-14 12:21 UTC by yamb00

# pull request template

Add key features to track bash

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/bash/blob/master/POLICIES.md)

2023-06-15 11:40 UTC, glennj commented
Configlet failures: https://github.com/exercism/bash/actions/runs/5267025041/jobs/9537788883?pr=634

Do this and address the issues:
```sh
./bin/fetch-configlet
./bin/configlet lint
```

2023-06-15 12:00 UTC, glennj requested changes

2023-06-15 12:00 UTC, glennj commented on config.json
> +      "content": "Bash scripts can be used with scheduling tools like cron to automate tasks at specific intervals.",
Lots of other languages work with cron.

Some other key aspects of bash for your consideration:
* pipelines to glue utilities together
* bash is widely available: portable, cross-platform
* concurrency: background processes and bash coprocesses
* interactive: same language that you use interactively

2023-06-22 14:15 UTC, glennj commented
@yamb00 I hope I didn't scare you off. I'd love to see an update for your PR.

2023-06-27 16:05 UTC, yamb00 commented
> @yamb00 I hope I didn't scare you off. I'd love to see an update for your PR.



> @yamb00 I hope I didn't scare you off. I'd love to see an update for your PR.

I just had no time to work on this

2023-06-27 18:35 UTC, glennj approved these changes
Nice! Thanks for this.

2023-06-27 18:35 UTC, glennj commented
@IsaacG want to weigh in?

2023-07-03 13:03 UTC, merged